// Code generated by sqlc. DO NOT EDIT.
// source: schema.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user, pass) VALUES (?, ?)
`

type CreateUserParams struct {
	User string
	Pass string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.User, arg.Pass)
	return err
}
